### PR TITLE
 added <pre> tag to table data to preserve new lines

### PR DESCRIPTION
**Pull request by dhoomakethu**
I needed this features as my JSON had values with multiline string , with <pre> the newlines could be preserved and will be presented with better formatting.

### CODE REVIEW

**Comment by softvar** [comment]
Tests have failed and I think it's not necessary.

Can you please add the screenshots, before and after the change? Would help a lot.

**Comment by muellermichel** [comment]
I think in general the pre-tag may make sense, however this is the wrong way to do it IMO. With this implementation *everything* within a td, including sub tables, sub lists, sub objects, gets wrapped in a <pre>. This could lead to lots of unwanted behaviour. Instead IMO it should be done on line 112 in markup, just for unicode elements.

**Comment by dhoomakethu** [comment]
Oops, I raised the PR by mistake ,apologies for that.I was in a bit of hurry, so did not modified the tests, , I will update them as well. J
ust for the sake of clarification , here is the issue and how the pre tag solves the formatting.
Without "**pre**"  tag

screen shot 2016-05-27 at 8 18 19 am

With "**pre**" tag

screen shot 2016-05-27 at 8 18 12 am

I agree with @muellermichel 's comment ,this is a fast cooked solution solving my current problem, I probably shouldn't have had the PR raised , I will decline the PR .

**Comment by softvar** [comment]
Please don't feel offended. Take your time. I really appreciate the patch.
Would love to see it getting merged soon :)

**Pull request closed without merging**
