### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by Nikolai-Hlubek**
A version of json2html with python3 support. 

jsonconv.py works with Python3.4. 

For python2 and 3 support I created branching in the __init__.py, but this is untested because I don't have python2 in the office.

### CODE REVIEW

**Comment by softvar** [comment]
@Nikolai-Hlubek Thanks for the pathc and adding support for python3.
Have you tested for python3? I'll take care of python2 version.

The only change I can see is changing `orderdict` to `collections`. If this is the case, instead of having another file, can we just put the condition where we have to use `collections` instead of `orderdict`?

@muellermichel - If you have some time, please review it, you're a great contributor in this.

**Comment by muellermichel** [comment]
Hey @softvar. I agree, I also think it's not a good idea to keep two different files, maintaining this would be an unnecessary pain in the future. I haven't really got any spare time atm, but I recommend just manually running a diff over the two files to see whether @Nikolai-Hlubek did something else to it, and then branching between these two versions in the original jsonconv. Also, as far as I can see, python 2.7 has backported OrderedDict in the collections package as well, so if I were you I'd just use it for both versions. What we need to be most careful of here, is unicode support since this differs quite a bit between python3.x and 2.x - a test class with some unicode testcases would make a lot of sense here, plus a testscript that runs it on python3.x and python2.x on the same system, so you can test this stuff before any release. I realize that this just a hobby project however, and I unfortunately don't have the time until probably spring 2016, so it's up to you if you want to do that plunge earlier.

**Comment by Nikolai-Hlubek** [comment]
In principle, to make it work, I had to do three changes: 

OrderedDict now found in collections 
I changed the import. If this is really backported this adaptation will be trivial.

iteritems -> items
This method was changed and it occurs once in the code. 

Strings are unicode per default
I removed the unicode casts as python3 strings are unicode by default. 

To support python2/3 in one file we would need to make the branching in the jsonconv and map items->iteritems for python2 and unicode->str for python3 or the other way around.

**Comment by muellermichel** [comment]
I'd say one could just define a helper function 'cast_to_unicode' and branch within that function to either `str` or `unicode` for the two versions. Then simply replace all `unicode` calls in the original file to this new helper function.

**Comment by softvar** [comment]
Will be removing `Ordereddict` now which will make this module python3 supported.

**Comment by softvar** [comment]
Have fixed this in latest stable version `1.0.0`. Removed `Orderdict`

**Comment by muellermichel** [comment]
Great stuff Varun!

**Comment by softvar** [comment]
@muellermichel Thanks!
The work was due for a long time. Now, I surely feel good :)

**Pull request closed without merging**
